config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#index'
  resources :dashboard, only: [:index]
  resources :links
  resources :tags do
    get 'from_users', on: :collection
    get 'from_page', on: :collection
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :user
  acts_as_taggable
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]

  has_many :links
  attr_writer :login
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @links = current_user.links
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  before_action :authenticate_user!

  def new
    @link = Link.new
  end

  def create
    link_service = LinkService.new(link_params)
    return errors unless link_service.save
    redirect_to dashboard_index_path
  end

  private

  def link_params
    params.require(:link).permit(:url, :tag_list).merge(
      user: current_user
    )
  end

  def errors
    flash.now[:danger] = 'Failed to save link'
    render :new
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  def create
    super
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :authenticate_user!

  def from_users
    return unless links
    render json: links.tag_counts.to_json
  end

  def from_page
    tags = FindTagsInUrl.new(params[:url]).top_tags
    return unless tags.present?
    render json: tags.to_json
  end

  private

  def links
    formated_url = FormatUrl.new(params[:url]).formated_url
    @links ||= Link.where(formated_url: formated_url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/links_helper.rb
# frozen_string_literal: true

module LinksHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/dashboard/index.html.erb
<ul class="list-group">
  <% @links.each do |link| %>
    <li class="list-group-item">
      <%= link.url %>
      <% link.tags.each do |tag| %>
        <span class="badge badge-primary badge-pill"><%= tag.name %></span>
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add a link', new_link_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <% if flash.any? %>
        <div id='errors' class="text-center">
          <% flash.each do |type, messages| %>
            <div class="alert alert-<%= type %>">
              <%= messages.is_a?(Array) ? messages.join(', ') : messages %>
            </div>
          <% end %>
        </div>      
      <% end %>

      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/create.html.erb
<h1>Links#create</h1>
<p>Find me in app/views/links/create.html.erb</p>

app/views/links/destroy.html.erb
<h1>Links#destroy</h1>
<p>Find me in app/views/links/destroy.html.erb</p>

app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

app/views/links/new.html.erb
<h1>Add a new link</h1>
<%= form_with model: @link do|f| %>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: 'http://www.example.com/' %>
  </div>

  <div class="form-group">
    <%= f.label :tag_list, 'Tags seperate with comma (,)' %>
    <%= f.text_field :tag_list, class: 'form-control', placeholder: 'news, sport, etc..' %>
  </div>
  <div id="suggested-tags" class="d-none">
    <h5>Suggested Tags</h5>
  </div>
  <div id="suggested-tags-from-page" class="d-none">
    <h5>Suggested Tags from page</h5>
  </div>
  <%= f.submit 'Save', class: 'btn btn-large btn-default' %>

<% end %>

app/views/links/update.html.erb
<h1>Links#update</h1>
<p>Find me in app/views/links/update.html.erb</p>

app/views/pages/index.html.erb
<div class='container'>
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Dashboard', dashboard_index_path %>
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= dashboard_index_path %>">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_link_path %>">Add a URL</a>
        </li>


      </ul>
      <%= link_to 'Logut', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </div>
  </nav>
<% end %>